# Generated by Django 2.2 on 2019-08-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, upload_to='board/image/'),
        ),
        migrations.AlterField(
            model_name='board',
            name='stat',
            field=models.CharField(choices=[('I', '공지사항'), ('F', '자유게시판')], max_length=10),
        ),
    ]
